# Generated by Django 3.1.6 on 2021-03-19 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('name_pinyin', models.CharField(max_length=30)),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')])),
                ('password', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=10)),
                ('dimission', models.SmallIntegerField(choices=[(0, '离职'), (1, '在职')], default=1)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'emp_info',
            },
        ),
        migrations.CreateModel(
            name='special_calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('date_type', models.IntegerField()),
                ('emp_info_id', models.CharField(blank=True, max_length=400, null=True)),
                ('work_hours', models.IntegerField()),
            ],
            options={
                'db_table': 'special_calendar',
            },
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('emp_id', models.ManyToManyField(to='dbModel.emp_info')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='ot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('ot_type', models.SmallIntegerField(choices=[(1, 'A1：新增需要、修改多'), (2, 'A2：临时增加项目、需求或者修改'), (3, 'A3：资料提供晚，拖延'), (4, 'B1：效率低'), (5, 'B2：正确率低'), (6, 'C：协助其他组员，或者SPC项目')])),
                ('weekday', models.SmallIntegerField(choices=[(1, '是'), (2, '否')])),
                ('ot_hours', models.IntegerField()),
                ('reason', models.CharField(max_length=30)),
                ('onl', models.CharField(max_length=20)),
                ('meel_fee', models.FloatField()),
                ('taxi_fee', models.FloatField()),
                ('ot_request_time', models.TimeField(blank=True, null=True)),
                ('ot_path', models.FilePathField(blank=True, null=True)),
                ('approve', models.SmallIntegerField(choices=[(0, '待审批'), (1, '已审批'), (2, '取消')])),
                ('emp_id', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, related_name='ot_emp_id', to='dbModel.emp_info', to_field='emp_id')),
            ],
            options={
                'db_table': 'ot',
            },
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('date_end', models.DateField()),
                ('leave_type', models.SmallIntegerField(choices=[(1, '法定年假'), (2, '福利年假'), (3, '病假'), (4, '倒休'), (5, '恩假'), (6, '计划生育假'), (7, '陪产假'), (8, '无薪假')])),
                ('leave_from', models.CharField(max_length=300)),
                ('leave_days', models.FloatField()),
                ('start_duration', models.SmallIntegerField(choices=[(0, '全天'), (1, '上午'), (2, '下午')])),
                ('end_duration', models.SmallIntegerField(choices=[(0, '全天'), (1, '上午'), (2, '下午')])),
                ('reason', models.CharField(max_length=30)),
                ('approve', models.SmallIntegerField(choices=[(0, '待审批'), (1, '已审批'), (2, '取消')], default=0)),
                ('emp_id', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, to='dbModel.emp_info', to_field='emp_id')),
            ],
            options={
                'db_table': 'leave',
            },
        ),
        migrations.CreateModel(
            name='group_rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('emp_id', models.ManyToManyField(to='dbModel.emp_info')),
            ],
            options={
                'db_table': 'group_rule',
            },
        ),
        migrations.CreateModel(
            name='function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fun_type', models.SmallIntegerField(choices=[(1, 'List'), (2, 'Button')])),
                ('explain', models.CharField(max_length=100)),
                ('role_id', models.ManyToManyField(to='dbModel.role')),
            ],
            options={
                'db_table': 'function',
            },
        ),
        migrations.CreateModel(
            name='account_leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.FloatField(default=12.5, verbose_name='sick leave')),
                ('sal', models.FloatField(default=5, verbose_name='Statutory Annual Leave')),
                ('bal', models.FloatField(default=10, verbose_name='Benefit Annual Leave')),
                ('lwp', models.FloatField(default=0, verbose_name='Leave Without Pay')),
                ('emp_id', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, to='dbModel.emp_info', to_field='emp_id', unique=True)),
            ],
            options={
                'db_table': 'account_leave',
            },
        ),
        migrations.CreateModel(
            name='account_compoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compoff_home_wd', models.FloatField(default=0)),
                ('compoff_office_wd', models.FloatField(default=0)),
                ('compoff_office_we', models.FloatField(default=0)),
                ('compoff_home1', models.FloatField(default=0)),
                ('compoff_home2', models.FloatField(default=0)),
                ('compoff_home3', models.FloatField(default=0)),
                ('compoff_office1', models.FloatField(default=0)),
                ('compoff_office2', models.FloatField(default=0)),
                ('compoff_office3', models.FloatField(default=0)),
                ('emp_id', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, to='dbModel.emp_info', to_field='emp_id', unique=True)),
            ],
            options={
                'db_table': 'account_compoff',
            },
        ),
        migrations.CreateModel(
            name='day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('st_om', models.TimeField(blank=True, null=True, verbose_name='start time office manual')),
                ('st_os', models.TimeField(blank=True, null=True, verbose_name='start time office system')),
                ('reason', models.CharField(blank=True, max_length=30, null=True)),
                ('et_o', models.TimeField(blank=True, null=True, verbose_name='end time office')),
                ('wh', models.IntegerField(verbose_name='work hours')),
                ('wh_o', models.IntegerField(default=0, verbose_name='work hours office')),
                ('wh_ot', models.IntegerField(default=0, verbose_name='work hours OT')),
                ('st_h', models.TimeField(blank=True, null=True, verbose_name='start time home')),
                ('et_h', models.TimeField(blank=True, null=True, verbose_name='end time home')),
                ('wh_h', models.IntegerField(default=0, verbose_name='work hours home')),
                ('st_h_path', models.FilePathField(blank=True, null=True)),
                ('et_h_path', models.FilePathField(blank=True, null=True)),
                ('ot_path', models.FilePathField(blank=True, null=True)),
                ('emp_id', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, to='dbModel.emp_info', to_field='emp_id')),
            ],
            options={
                'db_table': 'day',
                'unique_together': {('emp_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='account_pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('wd_ot', models.FloatField(default=0)),
                ('holiday_ot', models.FloatField(default=0)),
                ('we_ot', models.FloatField(default=0)),
                ('we_ot_lock', models.SmallIntegerField(choices=[(0, '未付费'), (1, '已付费'), (2, '被拒')], default=0)),
                ('emp_id', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, to='dbModel.emp_info', to_field='emp_id')),
            ],
            options={
                'db_table': 'account_pay',
                'unique_together': {('emp_id', 'year', 'month')},
            },
        ),
    ]
