# Generated by Django 3.1.6 on 2021-03-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ot',
            name='ot_path',
            field=models.FilePathField(blank=True, max_length=200, null=True),
        ),
    ]
