# Generated by Django 3.1.6 on 2021-03-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModel', '0002_auto_20210319_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='et_h_path',
            field=models.FilePathField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='ot_path',
            field=models.FilePathField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='st_h_path',
            field=models.FilePathField(blank=True, max_length=200, null=True),
        ),
    ]
