# Generated by Django 3.1.6 on 2021-03-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModel', '0003_auto_20210319_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ot',
            name='ot_type',
            field=models.SmallIntegerField(choices=[(1, 'A1：新增需要、修改多'), (2, 'A2：临时增加项目、需求或者修改'), (3, 'A3：资料提供晚，拖延'), (4, 'B1：效率低'), (5, 'B2：正确率低'), (6, 'C：协助其他组员，或者SPC项目'), (21, '数据量大/时间紧张'), (22, '特殊要求'), (23, '协助其他组员'), (41, '等数据'), (42, '需求晚'), (43, '需求多'), (44, 'QC'), (45, '项目时间紧'), (46, '车展'), (47, '应CS要求standby'), (48, '带交付项目多'), (49, '协助其他组员'), (61, '工作繁重')]),
        ),
        migrations.AlterField(
            model_name='ot',
            name='reason',
            field=models.CharField(max_length=100),
        ),
    ]
