# Generated by Django 3.1.6 on 2021-03-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModel', '0004_auto_20210324_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='group_rule',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
