# Generated by Django 3.1.6 on 2021-03-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModel', '0005_auto_20210326_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='ot',
            name='ot_request_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
