# Generated by Django 3.1.6 on 2021-03-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModel', '0006_ot_ot_request_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='special_calendar',
            old_name='emp_info_id',
            new_name='used_for',
        ),
        migrations.AlterField(
            model_name='emp_info',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
