# Generated by Django 3.1.6 on 2021-03-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModel', '0007_auto_20210329_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_calendar',
            name='work_hours_special',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp_info',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ot',
            name='ot_type',
            field=models.SmallIntegerField(choices=[(1, 'A1：新增需要、修改多'), (2, 'A2：临时增加项目、需求或者修改'), (3, 'A3：资料提供晚，拖延'), (4, 'B1：效率低'), (5, 'B2：正确率低'), (6, 'C：协助其他组员，或者SPC项目'), (21, '数据量大/时间紧张'), (22, '特殊要求'), (23, '协助其他组员'), (41, '等数据'), (42, '需求晚'), (43, '需求多'), (44, 'QC'), (45, '项目时间紧'), (46, '车展'), (47, '应CS要求standby'), (48, '待交付项目多'), (49, '协助其他组员'), (50, '加班等跑表完成后当天交付'), (61, '工作繁重')]),
        ),
    ]
