# Generated by Django 3.1.6 on 2021-04-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModel', '0008_auto_20210330_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_compoff',
            name='compoff_home_wd2',
            field=models.FloatField(default=0),
        ),
    ]
