# Generated by Django 3.1.6 on 2021-05-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModel', '0009_account_compoff_compoff_home_wd2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ot',
            name='weekday',
            field=models.SmallIntegerField(choices=[(1, '是'), (2, '否'), (3, '节假日'), (4, '特殊日期')]),
        ),
    ]
