# Generated by Django 3.1.6 on 2021-05-14 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbModel', '0010_auto_20210514_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first', models.TimeField(blank=True, null=True, verbose_name='First In')),
                ('last', models.TimeField(blank=True, null=True, verbose_name='Last Out')),
                ('wh', models.IntegerField(verbose_name='work hours')),
                ('emp_id', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, to='dbModel.emp_info', to_field='emp_id')),
            ],
            options={
                'db_table': 'attendance_day',
            },
        ),
    ]
