# Generated by Django 3.1.6 on 2021-07-16 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbModel', '0011_attendance_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.SmallIntegerField(choices=[(1, '法定年假'), (2, '福利年假'), (3, '病假'), (4, '倒休'), (5, '恩假'), (6, '计划生育假'), (7, '陪产假'), (8, '无薪假'), (9, '产检假')]),
        ),
        migrations.AlterUniqueTogether(
            name='attendance_day',
            unique_together={('emp_id', 'date')},
        ),
        migrations.CreateModel(
            name='compoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('compoff_type', models.SmallIntegerField(choices=[(1, '周末在公司'), (2, '节假日在公司'), (3, '平日在家'), (4, '周末/节假日在家')])),
                ('compoff_wh', models.IntegerField(verbose_name='compoff minutes')),
                ('approve', models.SmallIntegerField(choices=[(0, ''), (1, '已审批'), (2, '未审批'), (3, '未申请')], default=0)),
                ('status', models.SmallIntegerField(choices=[(1, '过期'), (2, '部分使用'), (3, '已使用'), (4, '未使用'), (5, '取消'), (6, '已核销')], default=4)),
                ('used_wh', models.IntegerField(verbose_name='used minutes')),
                ('emp_id', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, to='dbModel.emp_info', to_field='emp_id')),
            ],
            options={
                'db_table': 'compoff',
            },
        ),
    ]
