# Generated by Django 3.1.6 on 2021-07-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModel', '0012_auto_20210716_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoff',
            name='used_wh',
            field=models.IntegerField(blank=True, null=True, verbose_name='used minutes'),
        ),
    ]
