# Generated by Django 3.1.6 on 2021-07-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModel', '0013_auto_20210716_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='levNo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='compoff',
            name='approve',
            field=models.SmallIntegerField(choices=[(0, ''), (1, '已审批'), (2, '未审批'), (3, '未申请'), (4, '取消')], default=0),
        ),
    ]
