# Generated by Django 3.1.6 on 2021-08-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModel', '0014_auto_20210729_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_info',
            name='EntryDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
