# Generated by Django 3.1.6 on 2021-12-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModel', '0016_auto_20211201_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='ot_reason',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='ot_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, '不想回家'), (2, '补时长'), (3, '工作原因')], default=None, null=True),
        ),
    ]
