# Generated by Django 3.1.6 on 2022-02-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModel', '0017_auto_20211203_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_calendar',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
